### ISSUE TITLE
Changes in Add Product

### ISSUE THREAD

**Issue by muradhajiyev** [muradhajiyev/stores#106]
# Changes in Add Product

So, thans for your work.

Let's change a little bit in adding product.

1) In the Add Product Form, you have added "Choose Store" option. Let's remove it. 
Instead, put "Add Product" button in the Store - Products page. This button will be available for users who has only  'store' role. Additionally, if the store which store user entered doesn't belong to him, then we don't have to show add product button to him.
![store](https://user-images.githubusercontent.com/17532943/27066121-dfc49ff2-5012-11e7-8048-c99f5efbf82e.png)

2) Then, if store user click the "add product" button, you can call 
/products/create/45
 or 
/products/create?store=45 
route. 45 will be the store id.

**Comment by saria17** [comment]
done
