### ISSUE TITLE
Dropdowns bölməsi

### ISSUE THREAD

**Issue by muradhajiyev** [muradhajiyev/Stores#11]
Left navbar-da Specification Options deyə bölmə yaratmaq lazımdır.
Daha sonra bu bölməyə daxil olduqda bütün specificationların listini göstərək. 
Dropdowns tableda bir də display name column əlavə etmək gərəkdir. Hansı ki. ekranda göstərərkən display_name göstərək, tableları isə name-də olan ad ilə yaradaq.

List təqribi aşağıdakı kimi edək.

id | Name
1    Colors
2    Storages
3    Release_year (2010.2011,2012,2013,2014...)
4    Apple Laptop Product Family (Mac Air, Mac Pro, Powerbook, ....)

hər hansı dropdowna click etdikdə ətraflı olaraq onun daxilin olan dəyərləri siyahı şəklində göstərək (məs: Mac Air, Mac Pro, Powerbook, ....)

Yeni Dropdown Əlavə et buttona click etdikdə bunun üçün form açaq.

name: ._____________________
display_name ____________________
vallues ______________________  (vergül ilə)

**Comment by saria17** [comment]
display_name created in dropdowns table

**Comment by muradhajiyev** [comment]
Yoldaşlar, @saria17 @gnovruzov2018 

Dropdown baza arxitekturasında bir balaca dəyişiklik edək.
Deməli, əvvəl razılaşmışdıq ki, dropdown_source üçün dropdown name adı ilə eyni table yaradaq və həmin table-dan dropdown dəyərlərini götürək.

Aşağıdakı cədvəllərə baxın. Suallarınız olsa ətraflı müzakirə edərik.

**Specifications**
_id
name
type_id
unit_id
dropdown_id (nullable)_

**Dropdowns**
_id
name_

**Dropdown_values**
_dropdown_id
value_

1) Admin üçün ayrıca `Dropdowns ` deyə bölmə yaradaq. Bu bölməyə girdikdə istifadə olunacaq dropdown və onun qiymətlərini daxil edək.

name: ._____________________
vallues ______________________ (vergül ilə)
SAVE

dropdownun dəyərlərini **dropdown_values** cədvəlinə əlavə edək.

2) Admin üçün həm də `Specifications` deyə bölmə yaradaq. Bu bölməyə girdikdə isə specification, onun tipi, vahidi və əgər tip dropdown seçilərsə əvvəlcədən yaratdığımız dropdownlardan seçim imkanı verək.

name: __________________
type:  ____ select_box ______
unit: _____ select box _______
dropdown: ____ select_box ____ (make visible if dropdown type is selected)
SAVE


**Qeyd**: Bu daha yaxşı olacaq. Yenə baxın, daha yaxşı ideyalarınız olsa yazın müzakirə edək.

**Comment by muradhajiyev** [comment]
ƏLA
