### ISSUE TITLE
Minor Problem

### ISSUE THREAD

**Issue by muradhajiyev** [muradhajiyev/stores#185]
# Minor Problem

it is loaded 10 products in per page, But we have 12 items slot to show products in the Store page.

Link: http://13.95.154.68/store?page=2&store_id=131&store_name=Garda&page=1
![shopping](https://user-images.githubusercontent.com/17532943/28008867-40e56138-656a-11e7-9c30-5f39d9cd1d2c.png)

**Comment by saria17** [comment]
done
