### ISSUE TITLE
role_bug

### ISSUE THREAD

**Issue by muradhajiyev** [muradhajiyev/stores#24]
# User Role Bug
Deməli, user rolunda olan istifadəçi ilə sistemə girdikdən sonra /admin url-ə girmək mümkün olmamalıdır. 

 **/resources/views/403/403.blade.php**  bu adda fayl yaradın və içərisində 
403 Forbidden errorunu maraqlı mesaj şəklində göstərin.

Yəni bu url-ə girdikdə bu səhifə açılsın. Müvafiq səlahiyyətlərinin olmadığı mesajı çıxsın.

**Qeyd: Zəhmət olmasa pull request yaradarkən gördüyünüz işlər barəsində qısa qeyd edin.**

**Comment by saria17** [comment]
RedirectIfNotAdminOrStore middleware created.
