### ISSUE TITLE
specification_list_modification

### ISSUE THREAD

**Issue by muradhajiyev** [muradhajiyev/stores#25]
# Specification List

Deməli, @gnovruzov2018 

Əllərinə sağlıq qəşəng alınıb. Müəyyən dəyişikliklər etmək gərək olacaq.

1) Deməli, Specification list göstərərkən Typeİd, unitid,dropdownid yox onların adını qeyd edək.
2) Specification Edit edərkən yalnız onun adını, vahidini dəyişmək imkanı verək. (hələlik tip və dropdown id dəyişmək olmasın)
3) Dropdown edit edərkən isə adını və dəyərləri dəyişmək və yeni dəyər əlavə etmək mümkün olsun.

### ÖNƏMLİ:

İstər DropdownsController, istərsə də SpecificationsController də 4 funksiyanallıq var:
1) list all items
2) update item
3) delete item
4) insert new item

Sən bunun üçün web route-da ayrı-ayrı routelar qeyd etmisən. (dropdowns, dropdownForm, addDropdown, və s.)
Amma bunu belə etmək məsləhət deyil. Bu tip CRUD əməliyyatları üçün **Route::resource();** istifadə etmək lazımdır. Ətraflı aşağıdakı linkə baxarsan, sualların olsa soruş.

https://laravel.com/docs/5.4/controllers#resource-controllers

**Comment by saria17** [comment]
Hal-hazırda bunların üzərində işləyirəm

**Comment by muradhajiyev** [comment]
@saria17 @gnovruzov2018 

yoldaşlar, issue post-a əlavə etdim bir-balaca 

ÖNƏMLİ hissəsini də oxuyarsınız.

**Comment by saria17** [comment]
modifications done. edit in progress.
